### ISSUE TITLE
Henry Coefficient Fitting procedure ignoring data points

### ISSUE THREAD

**Issue by Surluson** [pauliacomi/pyGAPS#15]
The `initial_henry_slope` seems to be ignoring the dataset and favoring a henry coefficient of ~0 mmol/(g-bar) rather than trying to fit it to the data in some cases.

I tried running it on a few adsorption isotherms from the [NIST adsorption dataset](https://adsorbents.nist.gov/isodb/index.php#home) and ran into this problem for a few of them.

Here's a code snippet to reproduce this:
```
import pygaps
import requests
import json
import numpy as np

host = "adsorption.nist.gov"
url = "https://adsorption.nist.gov/isodb/api/isotherm/10.1021La803074g.isotherm3b.json"
isotherm_data = json.loads(requests.get(url).content)

pressure = [datapoint['pressure'] for datapoint in isotherm_data['isotherm_data']]
adsorption = [datapoint['species_data'][0]['adsorption'] for datapoint in isotherm_data['isotherm_data']]

isotherm = pygaps.PointIsotherm(
            pressure=pressure,
            loading=adsorption,
            material_name=isotherm_data['adsorbent']['name'],
            material_batch='',
            t_iso=isotherm_data['temperature'],
            adsorbate=isotherm_data['adsorbates'][0]['name'])
henry_coeff = pygaps.initial_henry_slope(isotherm, verbose=True)
```
![image](https://user-images.githubusercontent.com/21219867/60460059-97f2a600-9bf7-11e9-91ae-389416de951b.png)

Note I'm running pyGAPS version 1.6.1 on Python 3.7.3 and the above code was ran through using Jupyter Lab (using a virtualenv) on Ubuntu 16.04 LTS

I've taken a look at the code, and it looks to me that when the Henry fit isn't good enough, it should default to a fit between the first 2 points rather than flatlining.

Thank you,
-Árni

**Comment by pauliacomi** [comment]
Hi Arni,

I can confirm that the behaviour is as you described.

I do remember that the code is supposed to default to fit [0,0] and the first isotherm point if the fit isn't good enough. I'll look into this, likely before week is over as I am currently in the process of refactoring some code for the next version (expect 1.7/2.0 depending on the number of changes). 

By the way, you can load the isotherm directly from the ISODB using an inbuilt function (which actually uses `requests` under the hood).

```
import pygaps

iso_name = "10.1021La803074g.isotherm3b"
iso = pygaps.isotherm_from_isodb(iso_name)
```

should do the same thing.

Best,
Paul

**Comment by pauliacomi** [comment]
Hi Arni,

After a bit of digging, I found the reason for this behaviour.

When a pyGAPS "model" (such as Henry, Langmuir, etc) is fitted, an initial guess is generated for the model parameters based on a langmuir constant and saturation approximation. There was an error in how this initial guess was calculated:
```
langmuir_k = loading[0] / pressure[0] / (saturation_loading - pressure[0])
```
Instead of 
```
langmuir_k = loading[0] / pressure[0] / (saturation_loading - loading[0])
```
With most isotherms this was not a problem as the wrong value was "good enough" for a starting guess. On the other hand, when the isotherm had only one point (not including the [0,0]), the initial guess ended up negative or NaN, which led to minimisation problems.

I've made the above fix in the development branch of the code. The code snippet you provided should now work (provided you have the dev installed). If you have some time, could you check whether it fixes the problem on your end? If not, I suggest you wait until v2.0 is released over the weekend.

Best,
Paul

**Comment by Surluson** [comment]
Hi Paul,
Sorry for the late response, but your newest version did indeed fix the issue I was having.

Thanks for taking the time to actively continue developing PyGAPS!

Best,
Árni

**Comment by pauliacomi** [comment]
Hi Árni,

That's great to hear!
And thank you for the feedback. 
Please don't hesitate to let me know if you find any other bugs or inconsistencies.

Best,
Paul
