### ISSUE TITLE
IAST examples

### ISSUE THREAD

**Issue by xiaogongkui** [pauliacomi/pyGAPS#17]
For the IAST examples section, the following was given as an example, but the "%run import.ipynb" does not work and is there any reference as to which file was selected to give the information following the 3 imports? Thanks.

%run import.ipynb
import matplotlib.pyplot as plt
import numpy

Selected 5 isotherms with nitrogen at 77K
Selected 2 room temperature calorimetry isotherms
Selected 2 isotherms for IAST calculation
Selected 3 isotherms for isosteric enthalpy calculation

**Comment by pauliacomi** [comment]
The command is there to run the notebook called "import.ipnb" in the current kernel to import the example data. This notebook is found in the same folder i.e. `./docs/examples/import.ipynb`.

I've double checked it on my end at it works well. 

Can you make sure that you can run `import.ipynb` first? Also make sure that your root directory for jupyter is `./docs/examples/` otherwise the relative path will not work.

**Comment by xiaogongkui** [comment]
Hi Paul,

Thank you very much for the prompt reply. I followed your instruction and
got it to work. Thank you for sharing the wonderful work and time put into
the documentation.

Regards,
Gongkui

**Comment by pauliacomi** [comment]
Glad to hear it worked out! I will therefore close the issue if that's okay with you.

Don't hesitate to ask if you need any help or further info.

Best,
Paul
